import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import api from "../api/axios.js";
import { formatCurrency } from "../utils/currency.js";

export default function CustomerDashboard() {
  const [orders, setOrders] = useState([]);
  const [tickets, setTickets] = useState([]);
  const [ticket, setTicket] = useState({ subject: "", description: "", priority: "medium" });
  const [message, setMessage] = useState("");
  const load = () => Promise.all([api.get("/orders/myorders"), api.get("/support/mytickets")]).then(([ordersResponse, ticketsResponse]) => { setOrders(ordersResponse.data); setTickets(ticketsResponse.data); }).catch(() => setMessage("Unable to load account data"));
  useEffect(() => { load(); }, []);
  const createTicket = async (event) => { event.preventDefault(); try { await api.post("/support", ticket); setTicket({ subject: "", description: "", priority: "medium" }); setMessage("Support ticket created"); load(); } catch (error) { setMessage(error.response?.data?.message || "Unable to create ticket"); } };
  return <main className="dashboard-page"><div className="dashboard-heading"><div><p className="eyebrow">Your account</p><h1>Customer dashboard</h1></div><Link className="primary-button" to="/">Continue shopping <span>↗</span></Link></div><div className="stats-grid"><div className="stat-card"><span>Total orders</span><strong>{orders.length}</strong></div><div className="stat-card"><span>Open support</span><strong>{tickets.filter((item) => item.status !== "Closed" && item.status !== "Resolved").length}</strong></div><div className="stat-card"><span>Bag</span><strong><Link to="/cart">View</Link></strong></div></div><div className="customer-layout"><section><div className="dashboard-heading"><h2>Recent orders</h2><Link to="/orders">View all</Link></div>{orders.slice(0, 5).map((order) => <div className="order-card" key={order._id}><div><strong>#{order._id.slice(-6).toUpperCase()}</strong><p>{new Date(order.createdAt).toLocaleDateString()} · {order.items.length} items</p></div><div><span className="status">{order.status}</span><b>{formatCurrency(order.totalPrice)}</b></div></div>)}{!orders.length && <p className="muted">Your orders will appear here.</p>}</section><form className="dashboard-form" onSubmit={createTicket}><h2>Need help?</h2><input required value={ticket.subject} placeholder="Subject" onChange={(event) => setTicket({ ...ticket, subject: event.target.value })} /><textarea required value={ticket.description} placeholder="Tell us what happened" onChange={(event) => setTicket({ ...ticket, description: event.target.value })} /><select value={ticket.priority} onChange={(event) => setTicket({ ...ticket, priority: event.target.value })}><option value="low">Low priority</option><option value="medium">Medium priority</option><option value="high">High priority</option></select><button className="primary-button" type="submit">Open support ticket <span>↗</span></button>{message && <p className="form-note">{message}</p>}<div className="ticket-list">{tickets.slice(0, 3).map((item) => <p key={item._id}><strong>{item.subject}</strong><span>{item.status}</span></p>)}</div></form></div></main>;
}
